CREATE DATABASE portfolio;

CREATE TABLE blog (id SERIAL PRIMARY KEY, title TEXT NOT NULL, content TEXT NOT NULL);
CREATE TABLE comment (id SERIAL PRIMARY KEY, blog_id INTEGER REFERENCES blog(id), content TEXT);
CREATE TABLE users (name TEXT NOT NULL, email TEXT PRIMARY KEY, password TEXT NOT NULL);




INSERT INTO blog (title, content) VALUES ('promise in javascript', 'lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum');
INSERT INTO blog (title, content) VALUES ('react router', 'lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum');
INSERT INTO comment (blog_id, content) VALUES ('1', 'subscribed'), ('1', 'awesome blog'), ('1', 'love this'), ('2', 'keep it up'), ('2', 'great content');